baseURL = "https://atthaboon.github.io/PG-hugo-io/public/"
languageCode = "en-us"
title = "Robot Framework Puppeteer | Easy, Stable and Speed web testing"
theme = "timer-hugo"
publishDir = "docs"

# We Used Ionicons Icon font for Icon, for more details check this link - https://ionicons.com/

# Navbar Menus
[[menu.main]]
name    = "About"
url     = "about"
weight  = 2
[[menu.main]]
name    = "Service"
url     = "service"
weight  = 3
[[menu.main]]
name    = "Gallery"
url     = "gallery"
weight  = 4
[[menu.main]]
name    = "Blog"
url     = "blog"
weight  = 5
[[menu.main]]
name    = "Contact"
url     = "contact"
weight  = 6

# Site Params
[params]
home = "Home"
logo = "images/logo.png"
dateFormat = "6 January 2006"
# Meta data
description = "robotframework puppeteer automated web testing"
author = "QA Hive Co.,Ltd"
# Google Analitycs
googleAnalitycsID = "Your ID"
# contact form action
contactFormAction = "#" # contact form works with https://formspree.io

# Banner Section
[params.banner]
enable  = true
bgImage = "images/slider.jpg"
heading = "Start Your Test Project With"
description = "Easy, Stable and Speed web testing"
# button
btn     = true
btnText = "Quick Start"
btnURL  = "https://themefisher.com/"
# button
btn2     = true
btn2Text = "Download"
btn2URL  = "https://github.com/qahive/generator-robotframework-puppeteer/releases/download/0.1.2-1/rfp-test-project-page-object.zip"

# flip text
[[params.banner.flipText]]
title   = "Robot Framework - Puppeteer"

# Homepage About Section
[params.about]
enable  = true
title   = "Why Robot Framework Puppeteer?"
content = "Robot Framework Puppeteer created based on 3 core values"
image   = "images/about/about.jpg"

# Call to Action
[params.cta]
enable  = true
title   = "SO WHAT YOU THINK ?"
content = "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nobis,<br>possimus commodi, fugiat magnam temporibus vero magni recusandae? Dolore, maxime praesentium."
btnText = "Contact with me"
btnURL  = "/contact"

# Portfolio Section On Homepage
[params.portfolio]
enable  = true
title   = "Latest Works"
subtitle= "Aliquam lobortis. Maecenas vestibulum mollis diam. Pellentesque auctor neque nec urna. Nulla sit amet est. Aenean posuere tortor sed cursus feugiat, nunc augue blandit nunc, eu sollicitudin urna dolor sagittis lacus."

# social icon
[[params.socialIcon]]
icon = "ion-social-facebook"
url = "#"

[[params.socialIcon]]
icon = "ion-social-instagram"
url = "#"

[[params.socialIcon]]
icon = "ion-social-linkedin"
url = "#"
